mcc -m ind_baryc_pre ../../src/Rupture_areas/dist_wh.m ../../src/Rupture_areas/compute_distance2fault2D.m ...
    ../../src/Rupture_areas/ll2utm_utm2ll/ll2utm.m ...
    ../../src/Rupture_areas/ll2utm_utm2ll/utm2ll.m 